Repository COVESA/dlt-daemon, pull requests merged in 2024-05, with the labels that each got.

#609 dlt: Adaptation for QNX build system with SDP 7.x
  CMakeLists.txt
  qnx/.gitignore
  qnx/README.md
  qnx/build/Makefile
  qnx/build/common.mk
  qnx/build/nto-aarch64-le/Makefile
  qnx/build/nto-x86_64-o/Makefile
  qnx/build/qnx.nto.toolchain.cmake
  src/console/dlt-control-common.c
  tests/CMakeLists.txt
  tests/components/logd-converter/CMakeLists.txt
  tests/components/logstorage/disable_network/CMakeLists.txt
  tests/components/logstorage/logstorage_filepath/CMakeLists.txt
  tests/components/logstorage/logstorage_fsync/CMakeLists.txt
  tests/components/logstorage/logstorage_max_cache_size/CMakeLists.txt
  tests/components/logstorage/logstorage_multi_file/CMakeLists.txt
  tests/components/logstorage/logstorage_one_file/CMakeLists.txt
Labels: enhancement

#575 systemd: correct service files relationship
  systemd/dlt-dbus.service.cmake
  systemd/dlt-system.service.cmake
  systemd/dlt.service.cmake
Labels: refactor

#613 Close config file handle on error.
  src/daemon/dlt-daemon.c
Labels: bug

#630 dlt-system: add config to use uptime only
  doc/dlt-system.conf.5.md
  src/system/dlt-system-journal.c
  src/system/dlt-system-options.c
  src/system/dlt-system.conf
  src/system/dlt-system.h
Labels: enhancement
