Repository COVESA/dlt-daemon, pull requests merged in 2024-02, with the labels that each got.

#594 filetransfer: function added for cancelable filetransfer
  include/dlt/dlt_filetransfer.h
  src/examples/dlt-example-filetransfer.c
  src/lib/dlt_filetransfer.c
  tests/start_filetransfer_test.sh
Labels: enhancement, refactor

#593 Remove extra file number increment in name
  src/console/dlt-receive.c
Labels: bug

#595 systemd-watchdog: improve notifications to watchdog
  src/daemon/dlt-daemon.c
  src/daemon/dlt_daemon_common.c
  src/daemon/dlt_daemon_common.h
  src/daemon/dlt_daemon_event_handler.c
  src/daemon/dlt_daemon_socket.c
  tests/CMakeLists.txt
Labels: refactor
